spring:
  datasource:
    url: jdbc:mysql://localhost:3306/260school?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver